import turtle
import random
screen = turtle.Screen()
screen.screensize(500,500)
screen.bgcolor('black')
t = turtle.Turtle()
t2=turtle.Turtle()
t3=turtle.Turtle()
t2.hideturtle()
t3.hideturtle()
FORCE_FACTOR = 30

#intro screen
t.penup()
t.goto(60, 170)
t.pendown()
t.speed(0)
t.setheading(135)
t.fillcolor('cyan')
t.begin_fill()
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.end_fill()

t.penup()
t.goto(0, -200)
t.pendown()
screen.addshape('15 (1).gif')
t.shape('15 (1).gif')
t.stamp()
t.shape('classic')
t.penup()
t.goto(0, -200)
t.pendown()

t.penup()
t.goto(0, -100)
t.pendown()
screen.addshape('feb.gif')
t.shape('feb.gif')
t.stamp()
t.shape('classic')
t.penup()
t.goto(0, -100)
t.pendown()

t2.penup()
t2.pendown()
t2.write('My name is Dzenan and I am 15 I was born in February ', font=("ariel", 15, "italic"), align="center")
screen.bgcolor("white")
round = input("Press Enter to Continue: ")
t.clear()
t2.clear()




#second screen

t.penup()
t.goto(0, -200)
t.pendown()
screen.addshape('burger.gif')
t.shape('burger.gif')
t.stamp()
t.shape('classic')
t.penup()
t.goto(0, -200)
t.pendown()

t.penup()
t.goto(0, 200)
t.pendown()
screen.addshape('ic.gif')
t.shape('ic.gif')
t.stamp()
t.shape('classic')
t.penup()
t.goto(0, 200)
t.pendown()

t.penup()
t.goto(25, -125)
t.pendown()
#circle - radius
t.pencolor('blue')
t.circle(35)
t.penup()
screen.bgcolor('orange')
t2.write('Chicken, ice cream, burgers', font=("ariel", 30, "italic"), align="center")
round = input("Press Enter to Continue: ")
t.clear()
t2.clear()

#third screen

t.penup()
t.goto(0, -80)
t.pendown()
screen.addshape('mt.gif')
t.shape('mt.gif')
t.stamp()
t.shape('classic')
t.penup()
t.goto(0, -80)
t.pendown()

t.penup()
t.goto(0, -200)
t.pendown()
screen.addshape('sp.gif')
t.shape('sp.gif')
t.stamp()
t.shape('classic')
t.penup()
t.goto(0, -200)
t.pendown()

t.pencolor('green')
t.fillcolor('green')
t.begin_fill()
t.penup()
t.goto(25, 125)
t.pendown()
t.forward(100)
t.left(90)
t.forward(50)
t.left(90)
t.forward(100)
t.left(90)
t.forward(50)
t.end_fill()
screen.bgcolor('yellow')
t2.pendown()
t2.write('Playing sports, playing the game, watching movies, eating', font=("ariel", 15, "italic"), align="center")
round = input("Press Enter to Continue: ")
t.clear()
t2.clear()



#fourth screen

t.penup()
t.goto(0, -80)
t.pendown()
screen.addshape('r.gif')
t.shape('r.gif')
t.stamp()
t.shape('classic')
t.penup()
t.goto(0, -80)
t.pendown()

t.penup()
t.goto(0, -200)
t.pendown()
screen.addshape('rh.gif')
t.shape('rh.gif')
t.stamp()
t.shape('classic')
t.penup()
t.goto(0, -200)
t.pendown()

t.penup()
t.goto(150, 0)
t.pendown()
t.pencolor('blue')
t.fillcolor('blue')
t.begin_fill()
t.goto(250, 0)
t.goto(200,50)
t.goto(150, 0)
t.end_fill()
t.end_fill()
screen.bgcolor('tan')
t2.pendown()
t2.write('Rush Hour', font=("ariel", 30, "italic"), align="center")
round = input("Press Enter to Continue: ")
t.clear()
t2.clear()



#fifth screen

t.penup()
t.goto(0, 320)
t.pendown()
screen.addshape('gp.gif')
t.shape('gp.gif')
t.stamp()
t.shape('classic')
t.penup()
t.goto(0, 32000)
t.pendown()

t.penup()
t.goto(0, 200)
t.pendown()
screen.addshape('f.gif')
t.shape('f.gif')
t.stamp()
t.shape('classic')
t.penup()
t.goto(0, 200)
t.pendown()

t.penup()
t.goto(-56,-100)
t.pendown()
t.pencolor('yellow')
t.fillcolor('yellow')
t.begin_fill()
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.end_fill()
screen.bgcolor('pink')
t2.pendown()
t2.write('Football', font=("ariel", 30, "italic"), align="center")
round = input("Press Enter to Continue: ")
t2.clear()